### PR TITLE
fix(title-bar): correct broken link

### PR DESCRIPTION
**Pull request by DeeList**
change 'Update Available' url

### CODE REVIEW

**Review by pete-watters — APPROVED** [review]
Thanks @DeeList

**Review by kyranjamie — APPROVED** [review]
Thanks

**Comment by kyranjamie** [comment]
Can you reword commit to match conventional commit format?

**Comment by markmhx** [comment]
@DeeList the dev 💪

**Comment by pete-watters** [comment]
Thanks for fixing this @DeeList 👍 

I had to take your change into a new branch - https://github.com/leather-wallet/desktop/pull/1228 so I will close this one

**Pull request closed without merging**
